<?php

/* Script to create a table in the listeningtest.eu web space
 *  */

/* SERVER LOGIN
 * Declare variables and assign values for server log in.
 */

$servername = "mysql2269int.cp.blacknight.com";
$username = "u1099601_coleman";
$password = "Vtvvredr1746@";
$database = "db1099601_listeningTest";

// Create connection
$conn = new mysqli($servername, $username, $password, $database);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} else {
 echo "Success from the INITIAL CONNECT if statement" . "<br>";
 }
 echo "Connected successfully" . "<br>";


// Syntax to add a column to a table
//$sql = "ALTER TABLE subjectInfo 
//ADD fin_date TIMESTAMP;
//";

/* SQL TO CREATE TABLE
 * See here: https://www.w3schools.com/php/php_mysql_create_table.asp
 * ALSO: https://dev.mysql.com/doc/refman/8.0/en/integer-types.html (SQL explaining int types)
 */

/* this server-side table is hard-coded with presentation orders for use in tests 
  the 'id' field is an identifier, so we can pick an order to use */

//$sql = "CREATE TABLE EXP3_presOrder ( 
//  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
//  testStim1 SMALLINT(4) NOT NULL,
//  testStim2 SMALLINT(4) NOT NULL,
//  testStim3 SMALLINT(4) NOT NULL,
//  testStim4 SMALLINT(4) NOT NULL,
//  testStim5 SMALLINT(4) NOT NULL,
//  testStim6 SMALLINT(4) NOT NULL,
//  testStim7 SMALLINT(4) NOT NULL,
//  testStim8 SMALLINT(4) NOT NULL,
//  testStim9 SMALLINT(4) NOT NULL,
//  testStim10 SMALLINT(4) NOT NULL,
//  testStim11 SMALLINT(4) NOT NULL,
//  testStim12 SMALLINT(4) NOT NULL,
//  testStim13 SMALLINT(4) NOT NULL,
//  testStim14 SMALLINT(4) NOT NULL,
//  testStim15 SMALLINT(4) NOT NULL,
//  testStim16 SMALLINT(4) NOT NULL,
//  testStim17 SMALLINT(4) NOT NULL,
//  testStim18 SMALLINT(4) NOT NULL,
//  testStim19 SMALLINT(4) NOT NULL,
//  testStim20 SMALLINT(4) NOT NULL,
//  testStim21 SMALLINT(4) NOT NULL,
//  testStim22 SMALLINT(4) NOT NULL,
//  testStim23 SMALLINT(4) NOT NULL,
//  testStim24 SMALLINT(4) NOT NULL,
//  testStim25 SMALLINT(4) NOT NULL,
//  testStim26 SMALLINT(4) NOT NULL,
//  testStim27 SMALLINT(4) NOT NULL,
//  testStim28 SMALLINT(4) NOT NULL,
//  testStim29 SMALLINT(4) NOT NULL,
//  testStim30 SMALLINT(4) NOT NULL,
//  testStim31 SMALLINT(4) NOT NULL,
//  testStim32 SMALLINT(4) NOT NULL,
//  testStim33 SMALLINT(4) NOT NULL,
//  testStim34 SMALLINT(4) NOT NULL,
//  testStim35 SMALLINT(4) NOT NULL,
//  testStim36 SMALLINT(4) NOT NULL,
//  testStim37 SMALLINT(4) NOT NULL,
//  testStim38 SMALLINT(4) NOT NULL,
//  testStim39 SMALLINT(4) NOT NULL,
//  testStim40 SMALLINT(4) NOT NULL,
//  testStim41 SMALLINT(4) NOT NULL,
//  testStim42 SMALLINT(4) NOT NULL,
//  testStim43 SMALLINT(4) NOT NULL,
//  testStim44 SMALLINT(4) NOT NULL,
//  testStim45 SMALLINT(4) NOT NULL,
//  testStim46 SMALLINT(4) NOT NULL,
//  testStim47 SMALLINT(4) NOT NULL,
//  testStim48 SMALLINT(4) NOT NULL,
//  testStim49 SMALLINT(4) NOT NULL,
//  testStim50 SMALLINT(4) NOT NULL,
//  testStim51 SMALLINT(4) NOT NULL,
//  testStim52 SMALLINT(4) NOT NULL,
//  testStim53 SMALLINT(4) NOT NULL,
//  testStim54 SMALLINT(4) NOT NULL,
//  testStim55 SMALLINT(4) NOT NULL,
//  testStim56 SMALLINT(4) NOT NULL,
//  testStim57 SMALLINT(4) NOT NULL,
//  testStim58 SMALLINT(4) NOT NULL,
//  testStim59 SMALLINT(4) NOT NULL,
//  testStim60 SMALLINT(4) NOT NULL,
//  testStim61 SMALLINT(4) NOT NULL,
//  testStim62 SMALLINT(4) NOT NULL,
//  testStim63 SMALLINT(4) NOT NULL,
//  testStim64 SMALLINT(4) NOT NULL,
//  testStim65 SMALLINT(4) NOT NULL,
//  testStim66 SMALLINT(4) NOT NULL,
//  testStim67 SMALLINT(4) NOT NULL,
//  testStim68 SMALLINT(4) NOT NULL,
//  testStim69 SMALLINT(4) NOT NULL,
//  testStim70 SMALLINT(4) NOT NULL,
//  testStim71 SMALLINT(4) NOT NULL,
//  testStim72 SMALLINT(4) NOT NULL,
//  testStim73 SMALLINT(4) NOT NULL,
//  testStim74 SMALLINT(4) NOT NULL,
//  testStim75 SMALLINT(4) NOT NULL,
//  testStim76 SMALLINT(4) NOT NULL,
//  testStim77 SMALLINT(4) NOT NULL,
//  testStim78 SMALLINT(4) NOT NULL,
//  testStim79 SMALLINT(4) NOT NULL,
//  testStim80 SMALLINT(4) NOT NULL,
//  testStim81 SMALLINT(4) NOT NULL,
//  testStim82 SMALLINT(4) NOT NULL,
//  testStim83 SMALLINT(4) NOT NULL,
//  testStim84 SMALLINT(4) NOT NULL,
//  testStim85 SMALLINT(4) NOT NULL,
//  testStim86 SMALLINT(4) NOT NULL,
//  testStim87 SMALLINT(4) NOT NULL,
//  testStim88 SMALLINT(4) NOT NULL,
//  testStim89 SMALLINT(4) NOT NULL,
//  testStim90 SMALLINT(4) NOT NULL,
//  testStim91 SMALLINT(4) NOT NULL,
//  testStim92 SMALLINT(4) NOT NULL,
//  testStim93 SMALLINT(4) NOT NULL,
//  testStim94 SMALLINT(4) NOT NULL,
//  testStim95 SMALLINT(4) NOT NULL,
//  testStim96 SMALLINT(4) NOT NULL,
//  testStim97 SMALLINT(4) NOT NULL,
//  testStim98 SMALLINT(4) NOT NULL,
//  testStim99 SMALLINT(4) NOT NULL,
//  testStim100 SMALLINT(4) NOT NULL
//  )";
// 
// 
// // Below for creating subjectInfo table
// 
$sql = "CREATE TABLE EXP3_subjectInfo ( 
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reg_date TIMESTAMP,
  fin_date TIMESTAMP,
  age VARCHAR(30) NOT NULL,
  hearing_def VARCHAR(30) NOT NULL,
  gender VARCHAR(30) NOT NULL,
  handedness VARCHAR(30) NOT NULL,
  devicetype VARCHAR(30) NOT NULL,
  useragent VARCHAR(255) NOT NULL,
  trainStim0 SMALLINT(4) NOT NULL,
  trainResu0 TINYINT(3) NOT NULL,
  trainStim1 SMALLINT(4) NOT NULL,
  trainResu1 TINYINT(3) NOT NULL,
  trainStim2 SMALLINT(4) NOT NULL,
  trainResu2 TINYINT(3) NOT NULL,
  trainStim3 SMALLINT(4) NOT NULL,
  trainResu3 TINYINT(3) NOT NULL,
  trainStim4 SMALLINT(4) NOT NULL,
  trainResu4 TINYINT(3) NOT NULL,
  trainStim5 SMALLINT(4) NOT NULL,
  trainResu5 TINYINT(3) NOT NULL,
  testStim1 SMALLINT(4) NOT NULL,
  testResu1 TINYINT(3) NOT NULL,
  testStim2 SMALLINT(4) NOT NULL,
  testResu2 TINYINT(3) NOT NULL,
  testStim3 SMALLINT(4) NOT NULL,
  testResu3 TINYINT(3) NOT NULL,
  testStim4 SMALLINT(4) NOT NULL,
  testResu4 TINYINT(3) NOT NULL,
  testStim5 SMALLINT(4) NOT NULL,
  testResu5 TINYINT(3) NOT NULL,
  testStim6 SMALLINT(4) NOT NULL,
  testResu6 TINYINT(3) NOT NULL,
  testStim7 SMALLINT(4) NOT NULL,
  testResu7 TINYINT(3) NOT NULL,
  testStim8 SMALLINT(4) NOT NULL,
  testResu8 TINYINT(3) NOT NULL,
  testStim9 SMALLINT(4) NOT NULL,
  testResu9 TINYINT(3) NOT NULL,
  testStim10 SMALLINT(4) NOT NULL,
  testResu10 TINYINT(3) NOT NULL,
  testStim11 SMALLINT(4) NOT NULL,
  testResu11 TINYINT(3) NOT NULL,
  testStim12 SMALLINT(4) NOT NULL,
  testResu12 TINYINT(3) NOT NULL,
  testStim13 SMALLINT(4) NOT NULL,
  testResu13 TINYINT(3) NOT NULL,
  testStim14 SMALLINT(4) NOT NULL,
  testResu14 TINYINT(3) NOT NULL,
  testStim15 SMALLINT(4) NOT NULL,
  testResu15 TINYINT(3) NOT NULL,
  testStim16 SMALLINT(4) NOT NULL,
  testResu16 TINYINT(3) NOT NULL,
  testStim17 SMALLINT(4) NOT NULL,
  testResu17 TINYINT(3) NOT NULL,
  testStim18 SMALLINT(4) NOT NULL,
  testResu18 TINYINT(3) NOT NULL,
  testStim19 SMALLINT(4) NOT NULL,
  testResu19 TINYINT(3) NOT NULL,
  testStim20 SMALLINT(4) NOT NULL,
  testResu20 TINYINT(3) NOT NULL,
  testStim21 SMALLINT(4) NOT NULL,
  testResu21 TINYINT(3) NOT NULL,
  testStim22 SMALLINT(4) NOT NULL,
  testResu22 TINYINT(3) NOT NULL,
  testStim23 SMALLINT(4) NOT NULL,
  testResu23 TINYINT(3) NOT NULL,
  testStim24 SMALLINT(4) NOT NULL,
  testResu24 TINYINT(3) NOT NULL,
  testStim25 SMALLINT(4) NOT NULL,
  testResu25 TINYINT(3) NOT NULL,
  testStim26 SMALLINT(4) NOT NULL,
  testResu26 TINYINT(3) NOT NULL,
  testStim27 SMALLINT(4) NOT NULL,
  testResu27 TINYINT(3) NOT NULL,
  testStim28 SMALLINT(4) NOT NULL,
  testResu28 TINYINT(3) NOT NULL,
  testStim29 SMALLINT(4) NOT NULL,
  testResu29 TINYINT(3) NOT NULL,
  testStim30 SMALLINT(4) NOT NULL,
  testResu30 TINYINT(3) NOT NULL,
  testStim31 SMALLINT(4) NOT NULL,
  testResu31 TINYINT(3) NOT NULL,
  testStim32 SMALLINT(4) NOT NULL,
  testResu32 TINYINT(3) NOT NULL,
  testStim33 SMALLINT(4) NOT NULL,
  testResu33 TINYINT(3) NOT NULL,
  testStim34 SMALLINT(4) NOT NULL,
  testResu34 TINYINT(3) NOT NULL,
  testStim35 SMALLINT(4) NOT NULL,
  testResu35 TINYINT(3) NOT NULL,
  testStim36 SMALLINT(4) NOT NULL,
  testResu36 TINYINT(3) NOT NULL,
  testStim37 SMALLINT(4) NOT NULL,
  testResu37 TINYINT(3) NOT NULL,
  testStim38 SMALLINT(4) NOT NULL,
  testResu38 TINYINT(3) NOT NULL,
  testStim39 SMALLINT(4) NOT NULL,
  testResu39 TINYINT(3) NOT NULL,
  testStim40 SMALLINT(4) NOT NULL,
  testResu40 TINYINT(3) NOT NULL,
  testStim41 SMALLINT(4) NOT NULL,
  testResu41 TINYINT(3) NOT NULL,
  testStim42 SMALLINT(4) NOT NULL,
  testResu42 TINYINT(3) NOT NULL,
  testStim43 SMALLINT(4) NOT NULL,
  testResu43 TINYINT(3) NOT NULL,
  testStim44 SMALLINT(4) NOT NULL,
  testResu44 TINYINT(3) NOT NULL,
  testStim45 SMALLINT(4) NOT NULL,
  testResu45 TINYINT(3) NOT NULL,
  testStim46 SMALLINT(4) NOT NULL,
  testResu46 TINYINT(3) NOT NULL,
  testStim47 SMALLINT(4) NOT NULL,
  testResu47 TINYINT(3) NOT NULL,
  testStim48 SMALLINT(4) NOT NULL,
  testResu48 TINYINT(3) NOT NULL,
  testStim49 SMALLINT(4) NOT NULL,
  testResu49 TINYINT(3) NOT NULL,
  testStim50 SMALLINT(4) NOT NULL,
  testResu50 TINYINT(3) NOT NULL,
  testStim51 SMALLINT(4) NOT NULL,
  testResu51 TINYINT(3) NOT NULL,
  testStim52 SMALLINT(4) NOT NULL,
  testResu52 TINYINT(3) NOT NULL,
  testStim53 SMALLINT(4) NOT NULL,
  testResu53 TINYINT(3) NOT NULL,
  testStim54 SMALLINT(4) NOT NULL,
  testResu54 TINYINT(3) NOT NULL,
  testStim55 SMALLINT(4) NOT NULL,
  testResu55 TINYINT(3) NOT NULL,
  testStim56 SMALLINT(4) NOT NULL,
  testResu56 TINYINT(3) NOT NULL,
  testStim57 SMALLINT(4) NOT NULL,
  testResu57 TINYINT(3) NOT NULL,
  testStim58 SMALLINT(4) NOT NULL,
  testResu58 TINYINT(3) NOT NULL,
  testStim59 SMALLINT(4) NOT NULL,
  testResu59 TINYINT(3) NOT NULL,
  testStim60 SMALLINT(4) NOT NULL,
  testResu60 TINYINT(3) NOT NULL,
  testStim61 SMALLINT(4) NOT NULL,
  testResu61 TINYINT(3) NOT NULL,
  testStim62 SMALLINT(4) NOT NULL,
  testResu62 TINYINT(3) NOT NULL,
  testStim63 SMALLINT(4) NOT NULL,
  testResu63 TINYINT(3) NOT NULL,
  testStim64 SMALLINT(4) NOT NULL,
  testResu64 TINYINT(3) NOT NULL,
  testStim65 SMALLINT(4) NOT NULL,
  testResu65 TINYINT(3) NOT NULL,
  testStim66 SMALLINT(4) NOT NULL,
  testResu66 TINYINT(3) NOT NULL,
  testStim67 SMALLINT(4) NOT NULL,
  testResu67 TINYINT(3) NOT NULL,
  testStim68 SMALLINT(4) NOT NULL,
  testResu68 TINYINT(3) NOT NULL,
  testStim69 SMALLINT(4) NOT NULL,
  testResu69 TINYINT(3) NOT NULL,
  testStim70 SMALLINT(4) NOT NULL,
  testResu70 TINYINT(3) NOT NULL,
  testStim71 SMALLINT(4) NOT NULL,
  testResu71 TINYINT(3) NOT NULL,
  testStim72 SMALLINT(4) NOT NULL,
  testResu72 TINYINT(3) NOT NULL,
  testStim73 SMALLINT(4) NOT NULL,
  testResu73 TINYINT(3) NOT NULL,
  testStim74 SMALLINT(4) NOT NULL,
  testResu74 TINYINT(3) NOT NULL,
  testStim75 SMALLINT(4) NOT NULL,
  testResu75 TINYINT(3) NOT NULL,
  testStim76 SMALLINT(4) NOT NULL,
  testResu76 TINYINT(3) NOT NULL,
  testStim77 SMALLINT(4) NOT NULL,
  testResu77 TINYINT(3) NOT NULL,
  testStim78 SMALLINT(4) NOT NULL,
  testResu78 TINYINT(3) NOT NULL,
  testStim79 SMALLINT(4) NOT NULL,
  testResu79 TINYINT(3) NOT NULL,
  testStim80 SMALLINT(4) NOT NULL,
  testResu80 TINYINT(3) NOT NULL,
  testStim81 SMALLINT(4) NOT NULL,
  testResu81 TINYINT(3) NOT NULL,
  testStim82 SMALLINT(4) NOT NULL,
  testResu82 TINYINT(3) NOT NULL,
  testStim83 SMALLINT(4) NOT NULL,
  testResu83 TINYINT(3) NOT NULL,
  testStim84 SMALLINT(4) NOT NULL,
  testResu84 TINYINT(3) NOT NULL,
  testStim85 SMALLINT(4) NOT NULL,
  testResu85 TINYINT(3) NOT NULL,
  testStim86 SMALLINT(4) NOT NULL,
  testResu86 TINYINT(3) NOT NULL,
  testStim87 SMALLINT(4) NOT NULL,
  testResu87 TINYINT(3) NOT NULL,
  testStim88 SMALLINT(4) NOT NULL,
  testResu88 TINYINT(3) NOT NULL,
  testStim89 SMALLINT(4) NOT NULL,
  testResu89 TINYINT(3) NOT NULL,
  testStim90 SMALLINT(4) NOT NULL,
  testResu90 TINYINT(3) NOT NULL,
  testStim91 SMALLINT(4) NOT NULL,
  testResu91 TINYINT(3) NOT NULL,
  testStim92 SMALLINT(4) NOT NULL,
  testResu92 TINYINT(3) NOT NULL,
  testStim93 SMALLINT(4) NOT NULL,
  testResu93 TINYINT(3) NOT NULL,
  testStim94 SMALLINT(4) NOT NULL,
  testResu94 TINYINT(3) NOT NULL,
  testStim95 SMALLINT(4) NOT NULL,
  testResu95 TINYINT(3) NOT NULL,
  testStim96 SMALLINT(4) NOT NULL,
  testResu96 TINYINT(3) NOT NULL,
  testStim97 SMALLINT(4) NOT NULL,
  testResu97 TINYINT(3) NOT NULL,
  testStim98 SMALLINT(4) NOT NULL,
  testResu98 TINYINT(3) NOT NULL,
  testStim99 SMALLINT(4) NOT NULL,
  testResu99 TINYINT(3) NOT NULL,
  testStim100 SMALLINT(4) NOT NULL,
  testResu100 TINYINT(3) NOT NULL,
  trainPlay0 TINYINT(3) NOT NULL,
  trainPlay1 TINYINT(3) NOT NULL,
  trainPlay2 TINYINT(3) NOT NULL,
  trainPlay3 TINYINT(3) NOT NULL,
  trainPlay4 TINYINT(3) NOT NULL,
  trainPlay5 TINYINT(3) NOT NULL,
  testPlay1 TINYINT(3) NOT NULL,
  testPlay2 TINYINT(3) NOT NULL,
  testPlay3 TINYINT(3) NOT NULL,
  testPlay4 TINYINT(3) NOT NULL,
  testPlay5 TINYINT(3) NOT NULL,
  testPlay6 TINYINT(3) NOT NULL,
  testPlay7 TINYINT(3) NOT NULL,
  testPlay8 TINYINT(3) NOT NULL,
  testPlay9 TINYINT(3) NOT NULL,
  testPlay10 TINYINT(3) NOT NULL,
  testPlay11 TINYINT(3) NOT NULL,
  testPlay12 TINYINT(3) NOT NULL,
  testPlay13 TINYINT(3) NOT NULL,
  testPlay14 TINYINT(3) NOT NULL,
  testPlay15 TINYINT(3) NOT NULL,
  testPlay16 TINYINT(3) NOT NULL,
  testPlay17 TINYINT(3) NOT NULL,
  testPlay18 TINYINT(3) NOT NULL,
  testPlay19 TINYINT(3) NOT NULL,
  testPlay20 TINYINT(3) NOT NULL,
  testPlay21 TINYINT(3) NOT NULL,
  testPlay22 TINYINT(3) NOT NULL,
  testPlay23 TINYINT(3) NOT NULL,
  testPlay24 TINYINT(3) NOT NULL,
  testPlay25 TINYINT(3) NOT NULL,
  testPlay26 TINYINT(3) NOT NULL,
  testPlay27 TINYINT(3) NOT NULL,
  testPlay28 TINYINT(3) NOT NULL,
  testPlay29 TINYINT(3) NOT NULL,
  testPlay30 TINYINT(3) NOT NULL,
  testPlay31 TINYINT(3) NOT NULL,
  testPlay32 TINYINT(3) NOT NULL,
  testPlay33 TINYINT(3) NOT NULL,
  testPlay34 TINYINT(3) NOT NULL,
  testPlay35 TINYINT(3) NOT NULL,
  testPlay36 TINYINT(3) NOT NULL,
  testPlay37 TINYINT(3) NOT NULL,
  testPlay38 TINYINT(3) NOT NULL,
  testPlay39 TINYINT(3) NOT NULL,
  testPlay40 TINYINT(3) NOT NULL,
  testPlay41 TINYINT(3) NOT NULL,
  testPlay42 TINYINT(3) NOT NULL,
  testPlay43 TINYINT(3) NOT NULL,
  testPlay44 TINYINT(3) NOT NULL,
  testPlay45 TINYINT(3) NOT NULL,
  testPlay46 TINYINT(3) NOT NULL,
  testPlay47 TINYINT(3) NOT NULL,
  testPlay48 TINYINT(3) NOT NULL,
  testPlay49 TINYINT(3) NOT NULL,
  testPlay50 TINYINT(3) NOT NULL,
  testPlay51 TINYINT(3) NOT NULL,
  testPlay52 TINYINT(3) NOT NULL,
  testPlay53 TINYINT(3) NOT NULL,
  testPlay54 TINYINT(3) NOT NULL,
  testPlay55 TINYINT(3) NOT NULL,
  testPlay56 TINYINT(3) NOT NULL,
  testPlay57 TINYINT(3) NOT NULL,
  testPlay58 TINYINT(3) NOT NULL,
  testPlay59 TINYINT(3) NOT NULL,
  testPlay60 TINYINT(3) NOT NULL,
  testPlay61 TINYINT(3) NOT NULL,
  testPlay62 TINYINT(3) NOT NULL,
  testPlay63 TINYINT(3) NOT NULL,
  testPlay64 TINYINT(3) NOT NULL,
  testPlay65 TINYINT(3) NOT NULL,
  testPlay66 TINYINT(3) NOT NULL,
  testPlay67 TINYINT(3) NOT NULL,
  testPlay68 TINYINT(3) NOT NULL,
  testPlay69 TINYINT(3) NOT NULL,
  testPlay70 TINYINT(3) NOT NULL,
  testPlay71 TINYINT(3) NOT NULL,
  testPlay72 TINYINT(3) NOT NULL,
  testPlay73 TINYINT(3) NOT NULL,
  testPlay74 TINYINT(3) NOT NULL,
  testPlay75 TINYINT(3) NOT NULL,
  testPlay76 TINYINT(3) NOT NULL,
  testPlay77 TINYINT(3) NOT NULL,
  testPlay78 TINYINT(3) NOT NULL,
  testPlay79 TINYINT(3) NOT NULL,
  testPlay80 TINYINT(3) NOT NULL,
  testPlay81 TINYINT(3) NOT NULL,
  testPlay82 TINYINT(3) NOT NULL,
  testPlay83 TINYINT(3) NOT NULL,
  testPlay84 TINYINT(3) NOT NULL,
  testPlay85 TINYINT(3) NOT NULL,
  testPlay86 TINYINT(3) NOT NULL,
  testPlay87 TINYINT(3) NOT NULL,
  testPlay88 TINYINT(3) NOT NULL,
  testPlay89 TINYINT(3) NOT NULL,
  testPlay90 TINYINT(3) NOT NULL,
  testPlay91 TINYINT(3) NOT NULL,
  testPlay92 TINYINT(3) NOT NULL,
  testPlay93 TINYINT(3) NOT NULL,
  testPlay94 TINYINT(3) NOT NULL,
  testPlay95 TINYINT(3) NOT NULL,
  testPlay96 TINYINT(3) NOT NULL,
  testPlay97 TINYINT(3) NOT NULL,
  testPlay98 TINYINT(3) NOT NULL,
  testPlay99 TINYINT(3) NOT NULL,
  testPlay100 TINYINT(3) NOT NULL
  )";
// Check if table creation successful

if ($conn->query($sql) === TRUE) {
    echo "Table altered successfully";
} else {
    echo "Error creating table: " . $conn->error;
}

$conn->close();
?>